version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        # CodeDeploy replaces this placeholder with the new task definition ARN
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "app"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
